### ISSUE TITLE
Looks interesting - Questions...

### ISSUE THREAD

**Issue by gregberns** [travisghansen/oauth-external-auth-server#2]
Hey Travis, saw your repo referenced [here](https://github.com/containous/traefik/pull/3216) and it looks like this might apply to what I'm working on right now, but I'm not totally clear on the problem you're trying to solve.

I've got a docker swarm where I'm going to route all incoming traffic through Traefik, and expose KeyCloak for auth and a bunch of APIs will be protected with the forward auth Traefik supports.

Is this repo just doing the validation of the auth tokens? Or encrypting auth tokens so they're not visible in the outside world? Or supporting multiple identity providers? All the above? None?

I'm confused what the config token is for? Can you clarify a bit?

Please don't take any of the above negatively, the features list checks all the boxes I need to check, but I'm confused on the inner workings and some of the implementation. Any additional info you could provide would be appreciated. I'll keep digging through the code to understand more.

Here's two of my repos I've done POCs with where I think I'm implementing things right around this boundary:
https://github.com/gregberns/forward-auth
https://github.com/gregberns/identity-provider-demo

**Comment by travisghansen** [comment]
@gregberns thanks for the feedback!  Always great to get more eyes on a set of code.  I just looked at the diagram (I have my own that's similar but haven't committed to the repo yet) and it looks like there are some similarities.  There are from what I can tell some major differences as well.

It appears `forward-auth` is focused on replacing `KeyCloak` + more.  The `+ more` appears to be it's **also** attempting to `validate` the tokens which is more the focus of `keycloak-gatekeeper`.  So (if I'm understanding the doc correctly) `forward-auth` is:

- issuing tokens (what `keycloak` primary focuses on)
- validating tokens (what `keycloak-gatekeeper` primarily focuses on)

The general design is quite different from the `authorization code flow` that I'm primarily focused on.  I'm primarily focused on that flow because it allows for arbitrary services that don't understand `oauth`, `openid`, `jwt`, etc, etc to be protected by (when used with an appropriate setup) those concepts and infrastructure without needing application-level understanding/knowledge.

`forward-auth` more closely aligns with the `implicit` and `hybrid` flows (which may be better approaches particularly if you're trying to develop an api and the `client` has awareness of the things mentioned previously (`oauth`, `openid`, `jwt`, etc, etc).  I'm primarily focused on the `authorization code flow` but I do intend to support verifying `Bearer` tokens as well but it's not my current focus.

Digging through the code is probably a bit challenging several reasons so kudos for giving it a whirl!

- some of my comments are not cleaned up/proper
- it's alpha state (I have another sizable update coming early next week)
- the nature of being a sub-request makes some of the code conceptually recursive (it's kinda mind twisting)

To directly answer your questions:

- `Is this repo just doing the validation of the auth tokens?` - it's helping the user walk through a whole sign-in process.  `authorization code flow` facilitates the middleware (ie: this project) holding the token(s) directly instead of the user agent.  The tokens can in this case be verified by the middleware and/or the backing service should the service understand `Bearer` tokens etc.  I currently have configuration options to turn on/off much of this validation so it's not altogether required but by default it's making sure the token hasn't expired etc.  There is an option to send the token to the `Identity Provider` for `introspection` which can be thought of in some cases as a crude validation by the provider as well.  If you turned all the validation items off the only 'validation' happening is simply that the end-user was able to successfully authenticate with the provider (which is what many people are after).

- `Or encrypting auth tokens so they're not visible in the outside world?` - it holds the token(s) inside the server hiding the details from the user-agent/browser yes.  The are optionally passed to the backing service if desired.  Generally this is one of the ideas behind `authorization code flow`.  The service receives a `code` in the callback handler and then uses that code to retrieve token(s) on behalf of the user behind the scenes (ie: not visible to the user agent/browser, it's direct communication between the server and the identity provider).

- `Or supporting multiple identity providers?` - definitely this is one of the goals is to support multiple providers/configuration with a single deployment.  I was frustrated with the barrier to entry to simply/quickly secure a service.  I wanted something that could be deployed once and secure any arbitrary application **without needing to modify the application deployment**.  Leveraging forward/external auth features of the reverse proxies seems like a flexible and powerful enough approach but getting them to work with the `openid-connect` standard proved challenging particularly in light of 0 application deployment modifications.  So I got to work.

- `I'm confused what the config token is for?` - the `config_token` has nothing to do with authentication or oauth etc, think of it as the dynamic configuration of the app.  Instead per-deployment details being required (implicitly forcing things to be deployed multiple times like `oauth2_proxy` or `keycloak-gatekeeper` which each deployment has a static set of configuration), I'm simply taking the approach of storing each configuration as a `GET` parameter when setting up the reverse proxy.  Rather than use a block of url-encoded json, I wanted a mechanism that could be `signed` (to ensure legitimate consumers) and `encrypted` (to allow for separation of duties and concealing details like `client_id` and `client_secret` among other things).  Since `JWT` is already implied with `openid` I just decided to use that as the vehicle to fulfill the needs.  In short it's the manifestation of the dynamic configuration requirement.

To address your use-case specifically I'm not entirely sure this project fits the bill.  Or better said, I'm not entirely sure the `authorization code flow` fits the bill.  `authorization code flow` is really tailored towards end-users **browsing** to a service (all the crazy redirects and such) using a traditional web-browser UI IMO.  If you're trying to secure some APIs with a token the other flows likely better fit the need.  Again, I do intend to support the verification of `Bearer` tokens relatively soon which may or may not be what you're after.  When I do support that the likely use-case is to simply reject the request outright rather than attempting to redirect users all over the place to 'login' to a service and then make their way back to the service in a magical sequence of events, because who's logging into `keycloak` with curl right? :)

It's a long response, hopefully some of it's coherent and helpful.

**Comment by gregberns** [comment]
It was very coherent and incredibly helpful. The `forward-auth` example was my first couple steps back into auth since 2015. `identity-provider-demo` was understanding SAML and re-understanding OAuth/OIDC.
I believe I understand now why you're targeting `authorization code flow` specifically, thanks for the clarification.
I'm still trying to understand our (my company's) actual requirements, current and future. We're using a 'workflow' tool called Appian that will be making API calls and I still don't yet understand whether I need to use a 'machine 2 machine' workflow or the `authorization code flow`. So more work to do there :)
Its late so let me think about it some more, and I'll get back to you with questions. Thanks again for such a complete response, much appreciated.

**Comment by travisghansen** [comment]
@gregberns yeah sounds good.  It sounds like an option to consider would be an _API Gateway_, something like `Kong` using the `JWT` plugin.

- https://docs.konghq.com/hub/

**Comment by gregberns** [comment]
@travisghansen thanks for the suggestion, that definitely looks like something I may need to look into. Thanks for all the feedback.

**Comment by travisghansen** [comment]
@gregberns FYI I've decided to make the project scope more broad and support various plugins.  Some of the options you initially asked about will likely be covered in the longer term.  I'm implementing openid and ldap support initially.

**Comment by C-Duv** [comment]
Hello,
I discovered this project via Træfik (might be https://github.com/containous/traefik/pull/3216) and more or less like gregberns I had troubles understanding where it goes into an existing infrastructure and how it interacts between each parts.

Hopefully I found this issue were you explain more of the inner details of external-auth-server.
I still have questions but I know this project is still very young so instead of harassing you with questions about my use case, I'll wait for your sequence diagram to be committed.

**Comment by travisghansen** [comment]
@C-Duv I'd love to hear your use-case and get an understanding of what needs to be improved with the documentation to make the features and design more clear.  If you're on irc or similar let me know as it may be easier to simply chat.

For the `oauth2` and `oidc` plugins the flow is essentially as shown here: https://github.com/nokia/kong-oidc#how-does-it-work

**Comment by travisghansen** [comment]
@gregberns in my latest relates I implemented a `jwt` authentication plugin. This allows jwt `Bearer` tokens to be authenticated by the service.

@C-Duv anything I can help with for you?
